### ISSUE TITLE
Rigify generation issue:

### ISSUE THREAD

**Issue by Kaitou-3D** [absolute-quantum/cats-blender-plugin#326]
Hey team, Rigify if bugging out in the latest version when the addon is installed. The mmd_bone property will cause a hard failure and requires removal from all bones in order to proceed.
Repro steps:
1: install addon
2: add any Rigify metarig
3. Generate Rig
4. Error

![image](https://user-images.githubusercontent.com/26198203/145069278-19f5b3af-57db-45cf-88c2-aa6b66714a34.png)

**Comment by Mysteryem** [comment]
Looks like the Rigify issue that got fixed here:
https://github.com/blender/blender-addons/commit/905cfc4040e71bcc60d5526506814431bd0a8e58#diff-55ae5d14274d08a21c70760262df69df295152eb3755139088708f63287d5748

And looks like it didn't make it into the Blender 3.0 release: https://github.com/blender/blender-addons/blob/blender-v3.0-release/rigify/utils/mechanism.py#L472

**Comment by Shadaez** [comment]
while it might be fixed in rigify, cats shouldn't be assigning custom props in this way that causes it to break & have the properties not show up in the custom properties list

if anyone's having the issue use the blender addon Bone Layer to import a blank custom properties list and it'll fix the mmd_bone custom props not showing up, and then you can clean them out
