### ISSUE TITLE
Add specular bake ability

### ISSUE THREAD

**Issue by Tenshinen** [absolute-quantum/cats-blender-plugin#390]
I've been trying to use the bake panel and it seems there's no way to bake/atlas the Principled BSDF Specular input at all? It feels like I must be missing something but no matter what combination of bake passes I enable, none of them result in getting my specular textures back out again.
Assuming I'm not missing something, I feel this'd be very useful to add.

Example of my material setup: 
![image](https://user-images.githubusercontent.com/36275083/159077093-435e4f63-269f-4862-a51d-c40bd1aa1812.png)

**Comment by feilen** [comment]
Sadly we're limited to what Blender can produce. Blender's cycles rendering engine 'emulates' specularity by using it as a multiplier for how much specular light is reflected, but it can't really bake it natively since... it's ray-based and that's not really how light works.
I could see about just making it something that gets pulled into the 'emissive' channel and baked, as a sort of hold-over? (which is what we have to do for metalness, alpha, etc). In the mean time, you could try [converting to a PBR workflow](https://marmoset.co/posts/pbr-texture-conversion/).
