### ISSUE TITLE
eyes texture aways broken

### ISSUE THREAD

**Issue by iwanttokillyself** [absolute-quantum/cats-blender-plugin#656]
when I use the fix button the eyes texture now use another texture now?

**Comment by RinaDev-xyz** [comment]
What version of blender are you using, are you using the dev version of cats or a released version?

**Comment by iwanttokillyself** [comment]
released version


> What version of blender are you using, are you using the dev version of cats or a released version?

**Comment by RinaDev-xyz** [comment]
Again what version of blender are you using?

Also Make sure you use the dev version of cats:

https://github.com/absolute-quantum/cats-blender-plugin/tree/development
Direct link to zip file: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip

The current released versions will not work blender 3.6. I would even used the dev version on any version of blender which is 3.3 and above.

Also Blender 4.0 is also not supported by cats due to the fact cats has no been updated plus MMD tools which cats uses is outdated. I would either find a unofficial version which supports blender 4.0 or downgrade to blender 3.6.

**Comment by iwanttokillyself** [comment]
it work  thx
